config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :assets
  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
	belongs_to :variant
end

app/models/image.rb
class Image < Asset
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :variants
end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :product
  has_many :assets, :dependent => :delete_all
end

app/models/video.rb
class Video < Asset
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :set_asset, only: [:show, :edit, :update, :destroy]

  # GET /assets
  # GET /assets.json
  def index
    @assets = Asset.all
  end

  # GET /assets/1
  # GET /assets/1.json
  def show
  end

  # GET /assets/new
  def new
    @asset = Asset.new
  end

  # GET /assets/1/edit
  def edit
  end

  # POST /assets
  # POST /assets.json
  def create
    @asset = Asset.new(asset_params)

    respond_to do |format|
      if @asset.save
        format.html { redirect_to @asset, notice: 'Asset was successfully created.' }
        format.json { render :show, status: :created, location: @asset }
      else
        format.html { render :new }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assets/1
  # PATCH/PUT /assets/1.json
  def update
    respond_to do |format|
      if @asset.update(asset_params)
        format.html { redirect_to @asset, notice: 'Asset was successfully updated.' }
        format.json { render :show, status: :ok, location: @asset }
      else
        format.html { render :edit }
        format.json { render json: @asset.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assets/1
  # DELETE /assets/1.json
  def destroy
    @asset.destroy
    respond_to do |format|
      format.html { redirect_to assets_url, notice: 'Asset was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asset
      @asset = Asset.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def asset_params
      params.require(:asset).permit(:title, :description, :type, :url, :created_at)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.page(params[:page]).per(10)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :published)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/assets/_form.html.erb
<%= form_for(asset) do |f| %>
  <% if asset.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% asset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_field :type %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :created_at %>
    <%= f.text_field :created_at %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assets/edit.html.erb
<h1>Editing Asset</h1>

<%= render 'form', asset: @asset %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', assets_path %>

app/views/assets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Type</th>
      <th>Url</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assets.each do |asset| %>
      <tr>
        <td><%= asset.title %></td>
        <td><%= asset.description %></td>
        <td><%= asset.type %></td>
        <td><%= asset.url %></td>
        <td><%= asset.created_at %></td>
        <td><%= link_to 'Show', asset %></td>
        <td><%= link_to 'Edit', edit_asset_path(asset) %></td>
        <td><%= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asset', new_asset_path %>

app/views/assets/new.html.erb
<h1>New Asset</h1>

<%= render 'form', asset: @asset %>

<%= link_to 'Back', assets_path %>

app/views/assets/show.html.erb
<p id="notice"><%= notice %></p>

  <%= image_tag @asset.url %>

<p>
  <strong>Title:</strong>
  <%= @asset.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @asset.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @asset.class.name %>
</p>


<p>
  <strong>Created at:</strong>
  <%= @asset.created_at %>
</p>

<%= link_to 'Edit', edit_asset_path(@asset) %> |
<%= link_to 'Back', assets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssociationsTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :published %>
    <%= f.check_box :published %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>
<%= page_entries_info @products %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.published %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @products %>
<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<h3>
	Product details
</h3>
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Published:</strong>
  <%= @product.published %>
</p>


<h3>
	Variants
</h3>
<ul>
<% @product.variants.each do |variant| %>
	<li>
		<%= variant.title %>

		<ul>
			<% variant.assets.each do |asset| %>
				<li>
					<a href="/assets/<%= asset.id %>"><%= image_tag(asset.url) %></a>
				</li>
			<% end %>
		</ul>
	</li>
<% end %>
</ul>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>